services:
  mongodb:
    image: mongo:4.2
    container_name: mongo_DB
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lidigu
      - MONGO_INITDB_ROOT_PASSWORD=lidigu
  mongo-express:
    image: mongo-express
    container_name: mongo_expressed
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=lidigu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=lidigu
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}
